### ISSUE TITLE
Auto-calculate the batch size?

### ISSUE THREAD

**Issue by ajratner** [HazyResearch/bazaar#7]
@raphaelhoffmann Especially since the loading time of coreNLP is so (relatively) long, it seems like a better default than `batch_size=1000` would be to divide lines by the number of cores (or `cores*nodes` for distribute).  For example I just got a 2x speedup on an ec-2 node really easily here (had forgotten to set batch size first time around...).  Thoughts?

**Comment by raphaelhoffmann** [comment]
That's a great idea! Please check this in.

**Comment by ajratner** [comment]
Sure, will do tomorrow

**Comment by ajratner** [comment]
Will push my new wrapper functions (in the `fabfile`) when done processing everything...
